name: Arcy_RPG
version: '${project.version}'
main: org.main.Arcy_RPG
api-version: 1.19

commands:
#   coins:
#      description: Wyświetla ilość posiadanych ArcyCoins
#      usage: /coins
   register:
      description: Rejestruje gracza z tokenem
      usage: /register <token>
   help:
      description: Display the help message
      usage: /help
permissions:
   systemLogin.register:
      description: Allows the player to register with a token.
      usage: /register
      default: false
