name: Arcy_RPG
version: '${project.version}'
main: org.main.Arcy_RPG
api-version: 1.19

commands:
   gui:
      description: Otwórz GUI
      usage: /gui
   arcycoins:
      description: Wyświetla ilość posiadanych ArcyCoins
      usage: /<command>

